# Generated by Django 5.0.4 on 2024-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLOPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_category', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField()),
                ('model', models.JSONField()),
                ('created_user', models.CharField(max_length=100)),
                ('model_description', models.CharField(max_length=200)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_user', models.CharField(max_length=100)),
            ],
        ),
    ]
